[package]
name = "accumulator-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.accumulator]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.50.2"
default-features = false
