// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           20
// Async Callback (empty):               1
// Total number of exported functions:  23

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    accumulator
    (
        init => init
        upgrade => upgrade
        deposit => deposit
        depositRoyalties => deposit_royalties
        distribute => distribute
        distributeRoyalties => distribute_royalties
        claimProtocolReserves => claim_protocol_reserves
        getRevenue => revenue
        getRewardToken => reward_token
        getLiquidRewardToken => liquid_reward_token
        getBurnRate => burn_rate
        getShareRate => share_rate
        getAccumulatedTokens => tokens
        getAccumulatedTokenBalance => token_balance
        getCreators => creators
        getCreatorTokens => creator_tokens
        getCreatorRoyalties => creator_royalties
        getLiquidSC => xoxno_liquid_sc
        getAggregatorSC => ash_sc
        queryCreatorRoyalties => get_creator_royalties
        queryAllCreatorRoyalties => get_all_creator_royalties
        queryRealYieldPending => get_real_yield_pending
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
